version: "3.9"
services:
  api:
    build:
      context: ./backend
    container_name: portfolio-api
    env_file: .env
    volumes:
      - ./backend/app:/app/app
      - ./config.yaml:/app/config.yaml
      - ./frontend:/app/static
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
